feat: improve ci cd 6 (#10)
* fix: adapt the pod check in the case deployment rolled out failed

* fix: add deployment conditions check

diff --git a/tekton-platform/tasks/patch-deployment.yaml b/tekton-platform/tasks/patch-deployment.yaml
--- a/tekton-platform/tasks/patch-deployment.yaml
+++ b/tekton-platform/tasks/patch-deployment.yaml
@@ -28,6 +28,9 @@ spec:
     - name: deployment-timeout
       type: string
       description: The timeout for the deployment rollout check
+    - name: readiness-recheck-delay
+      type: string
+      description: Seconds to wait before rechecking pod readiness after rollout.
   steps:
     - name: create-deployment
       image: alpine/k8s:1.20.4
@@ -94,3 +97,15 @@ spec:
           echo "ERROR: Timeout or rollout failed!" >&2
           exit 1
         fi
+
+        echo "Rollout finished. Double checking Pods readiness..."
+        sleep "$(params.readiness-recheck-delay)"
+
+        UNREADY_PODS=$(kubectl get pods -n $NS -l app=$DEPLOY_NAME --field-selector status.phase=Running -o jsonpath='{range .items[*]}{.status.containerStatuses[*].ready}{"\n"}{end}' | grep -c "false" || true)
+
+        if [ "$UNREADY_PODS" -gt 0 ]; then
+          echo "ERROR: Rollout reported success, but $UNREADY_PODS pod(s) are NOT READY!" >&2
+          exit 1
+        fi
+
+        echo "Deployment is fully up and stable!"
